#!/usr/bin/env python3
import sys

from api_app import models
import datetime
import asyncio


async def create_user_admin():
    class Setting:
        def __init__(self):
            self.DATABASE_URI = "mongodb://localhost/appdb"

    settings = Setting()
    if len(sys.argv) > 1:
        settings.DATABASE_URI = "mongodb://mongodb/appdb"

    await models.init_beanie(settings)

    print("start check admin")
    user = await models.User.find_one(models.User.username == "admin")

    if user:
        print("Found admin user", user)
        return
    print("end check admin")

    print("start create admin")
    user = models.User(
        email="admin@example.com",
        username="admin",
        password="",
        first_name="admin",
        last_name="system",
        roles=["user", "admin"],
        status="active",
    )
    await user.set_password("p@ssw0rd")
    await user.save()
    print("finish")


if __name__ == "__main__":
    asyncio.run(create_user_admin())
